version: '3.8'
services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 8080:3000
      - 9229:9229
    command: yarn start:debug
    volumes:
      - /app/node_modues
      - ./src:/app/src

    # nest > nodemon > changes in files > hot reload
    # host FS > volumes < container FS

    # 1. Bind mount
      # features:
        # - two way sync
      # syntax:
        # ./src:/app/src

    # 2. Persistent volume
      # features:
        # - one way sync -> from container to host
        # - the only sync from host to container happens when we create volume
        # - data stored and maged by Docker -> /var/lib/docker/volumes/{random_hash}/_data
      # types:
        # - named
          # syntax:
            # - some_name_for_this_volume:/app/node_modules
          # features:
            # - sharing between different containers
            # - removal of container does not result in volume loss
        # - anonymous
          # syntax:
            # - /app/node_modues
          # features:
            # - can be used when we don't care about sharing or keeping data between container removals
            # - can be used for caching data / speed up build process

