version: '3.8'
services:
  ### redis ###
  redis:
    container_name: redis
    image: 'redis:alpine'
    ports:
      - 6379:${REDIS_PORT}
  ### postgres ###
  postgres:
    container_name: postgres
    image: postgres
    restart: unless-stopped
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USERNAME: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    networks:
      - postgres
  ### pgadmin ###
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    ports:
      - 5050:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:

  ### api ###
  # api:
  #   build:
  #     dockerfile: Dockerfile
  #     context: .
  #   ports:
  #     - 8080:3000
  #     - 9229:9229
  #   command: yarn start:debug
  #   volumes:
  #     - /app/node_modues
  #     - ./src:/app/src
  #   depends_on:
  #     - redis
  #   env_file: .env
