version: '3.8'
services:
  ### redis ###
  redis:
    image: 'redis:alpine'
    ports:
      - 6379:${REDIS_PORT}
  ### postgres ###
  postgres:
    image: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PORT}
      POSTGRES_USERNAME: ${DB_USERNAME}
    volumes:
      - .docker-data/postgres:/var/lib/postgresql/data

  ### api ###
  # api:
  #   build:
  #     dockerfile: Dockerfile
  #     context: .
  #   ports:
  #     - 8080:3000
  #     - 9229:9229
  #   command: yarn start:debug
  #   volumes:
  #     - /app/node_modues
  #     - ./src:/app/src
  #   depends_on:
  #     - redis
  #   env_file: .env
