version: '3.8'
services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 8080:5000
      - 9229:9229
    command: yarn start:debug
    volumes:
      - /app/node_modues
      - ./src:/app/src
